# MongoDB Container
mongo:
  # https://hub.docker.com/r/library/mongo/
  image: mongo:3.4
  # Run with --nojournal to prevent log saturation
  command: --nojournal
  container_name: secfiware_mongodb


# Orion Context-Broker Container
# C++ WebService that perform operations on the MongoDB via REST
orion:
  # https://hub.docker.com/r/fiware/orion/
  image: fiware/orion:1.10.0
  # This container only will start after mongo
  ports:
    - 1026:1026
  volumes:
    - ./cert.crt:/etc/orion-ssl/cert.crt
    - ./cert.key:/etc/orion-ssl/cert.key
  links:
    - mongo
  # Passing the -https parameter to enable Orion in HTTPS context.
  command: -dbhost mongo -https -key /etc/orion-ssl/cert.key -cert /etc/orion-ssl/cert.crt
  container_name: secfiware_orion

# LWM2M IoT Agent
iota:
  # https://hub.docker.com/r/m4n3dw0lf/dtls-lightweightm2m-iotagent
  image: m4n3dw0lf/dtls-lightweightm2m-iotagent
  net: host
  volumes:
    - ./cert.crt:/opt/iota-lwm2m/cert.crt
    - ./cert.key:/opt/iota-lwm2m/cert.key
